services:
  # Frontend (Static Site)
  - type: web
    name: shopper-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend API
  - type: web
    name: shopper-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: shopper-db
          property: connectionString

databases:
  - name: shopper-db
    databaseName: shopper
    user: shopper_user
